services:
  my_postgres:
    image: postgres:15
    restart: always
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5423:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
      

volumes:
  postgres_data:



