# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные среды для пользователя, базы данных и пароля
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Порт, который будет использоваться
EXPOSE 5432